import os
import sys
import subprocess
import json

class DigitizationEngine:
    def __init__(self):
        self.utils_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.utils_dir = os.path.join(self.utils_root, "python-utils")
        self.config_file = os.path.join(self.utils_root, "workspace_config.json")
        self.report_path = os.path.join(self.utils_dir, "temp_report.json")
        self.data_root = ""
        self.old_folder = "old-orthography"
        self.new_folder = "new-orthography"
        self.load_config()

    def load_config(self):
        """Loads workspace configuration from JSON, falling back to defaults."""
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, "r", encoding="utf-8") as f:
                    conf = json.load(f)
                    self.data_root = conf.get("data_root", "")
                    self.old_folder = conf.get("old_folder", "old-orthography")
                    self.new_folder = conf.get("new_folder", "new-orthography")
            except Exception:
                pass
        
        if not self.data_root:
            self.data_root = r"C:\github\Manannan"

    def save_config(self, data_root, old_folder, new_folder):
        """Saves current workspace configuration persistently."""
        self.data_root = data_root
        self.old_folder = old_folder
        self.new_folder = new_folder
        with open(self.config_file, "w", encoding="utf-8") as f:
            json.dump({
                "data_root": data_root,
                "old_folder": old_folder,
                "new_folder": new_folder
            }, f, indent=4)

    def run_ocr_fixer(self, input_file):
        """Executes the ocr_fixer.py script. Returns (success, stdout, stderr)"""
        cmd = [sys.executable, os.path.join(self.utils_dir, "ocr_fixer.py"), input_file, "--report", self.report_path]
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=self.utils_dir)
        return result.returncode == 0, result.stdout, result.stderr

    def run_modernizer(self, input_file):
        """Executes the convert_orthography.py script. Returns (success, output_path, stderr)"""
        output_path = input_file.replace(self.old_folder, self.new_folder)
        cmd = [sys.executable, os.path.join(self.utils_dir, "convert_orthography.py"), input_file, "--output", output_path]
        result = subprocess.run(cmd, capture_output=True, text=True, cwd=self.utils_dir)
        return result.returncode == 0, output_path, result.stderr

    def load_report(self):
        """Loads the ambiguous_matches report generated by the OCR fixer."""
        if os.path.exists(self.report_path):
            try:
                with open(self.report_path, 'r', encoding='utf-8') as f:
                    return json.load(f).get("ambiguous_matches", [])
            except Exception:
                return []
        return []

    def get_default_directory(self):
        """Returns the default directory for file selection based on current data root."""
        return os.path.join(self.data_root, "caibidlí", self.old_folder)

    def open_output_folder(self):
        """Opens the folder containing the modernized output through the host OS."""
        output_dir = os.path.join(self.data_root, "caibidlí", self.new_folder)
        if os.path.exists(output_dir):
            if sys.platform == "win32":
                os.startfile(output_dir)
            else:
                opener = "open" if sys.platform == "darwin" else "xdg-open"
                subprocess.call([opener, output_dir])
            return True
        return False
